#Quarkus will run on port 8081 (8080 is already used by keycloak)
quarkus.http.port=8081

#Postgresql Database Connection Configuration
quarkus.datasource.key.db-kind=postgresql
quarkus.datasource.key.username=postgres
quarkus.datasource.key.password=password
quarkus.datasource.key.jdbc.url=jdbc:postgres::/localhost:5433/app_db
quarkus.hibernate-orm.key.database.generation=drop-and-create

#Keycloak Configuration
quarkus.oidc.auth-server-url=http://localhost:8080/realms/wis-top-wheels-realm
quarkus.oidc.client-id=nextjs-client
quarkus.oidc.credentials.secret=ANZYYcCdORLQ84FlLnL7moC7aeN6lkauRHfmgf8W7bvyTsIAhX0i918GcJBGWWvdwLKA8DIULdgrUIXSdGcloN
quarkus.oidc.application-type=service