#Quarkus will run on port 8081 (8080 is already used by keycloak)
quarkus.http.port=8081

#Postgresql Database Connection Configuration
quarkus.datasource.key.db-kind=postgresql
quarkus.datasource.key.username=postgres
quarkus.datasource.key.password=password
quarkus.datasource.key.jdbc.url=jdbc:postgres::/localhost:5433/app_db
quarkus.hibernate-orm.key.database.generation=drop-and-create

#Keycloak Configuration
quarkus.oidc.auth-server-url=http://localhost:8080/realms/wis-top-wheels-realm
quarkus.oidc.client-id=nextjs-client
quarkus.oidc.credentials.secret=EuqL2hJTW8v2jCc0x8QLk23DdZt3rqAOkKhqfmmz3O8z97oo50unTLeMtCmTzuB31icjOJCZvzVcUO3ypmObbN
quarkus.oidc.application-type=service

#Keycloak Admin Client Configuration
quarkus.keycloak.admin-client.server-url=http://localhost:8080
quarkus.keycloak.admin-client.realm=wis-top-wheels-realm
quarkus.keycloak.admin-client.client-id=nextjs-client
quarkus.keycloak.admin-client.client-secret=EuqL2hJTW8v2jCc0x8QLk23DdZt3rqAOkKhqfmmz3O8z97oo50unTLeMtCmTzuB31icjOJCZvzVcUO3ypmObbN
quarkus.keycloak.admin-client.grant-type=client-credentials