# Quarkus will run on port 8081 (8080 is already used by keycloak)
quarkus.http.port=8081

# Postgresql Database Connection Configuration
quarkus.datasource.key.db-kind=postgresql
quarkus.datasource.key.username=${DB_USERNAME}
quarkus.datasource.key.password=${DB_PASSWORD}
quarkus.datasource.key.jdbc.url=${DB_URL}
quarkus.hibernate-orm.key.database.generation=drop-and-create

# Keycloak Configuration
quarkus.oidc.auth-server-url=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
quarkus.oidc.client-id=nextjs-client
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.oidc.application-type=service

# Keycloak Admin Client Configuration
quarkus.keycloak.admin-client.server-url=${KEYCLOAK_URL}
quarkus.keycloak.admin-client.realm=${KEYCLOAK_REALM}
quarkus.keycloak.admin-client.client-id=nextjs-client
quarkus.keycloak.admin-client.client-secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.keycloak.admin-client.grant-type=client-credentials